baseURL = "https://5h4rrK.github.io/"
languageCode = "en-us"
title = "5h4rrK "
theme = "hugo-PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = [ "posts", "hugo-PaperMod" ]

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

  [languages.en.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

  [languages.en.params]
  languageAltTitle = "English"

    [languages.en.params.profileMode]
    enabled = true
    title = "सभ्य  "
    imageUrl = "https://avatars.githubusercontent.com/u/89577007"
    imageTitle = "Profile image"
    imageWidth = 120
    imageHeight = 120
    subtitle = "  "

      [[languages.en.params.profileMode.buttons]]
      name = "Blog"
      url = "posts"

[params]
env = "production"
description = "5h4rrK's blog"
author = "Sabhya Raj"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true

  [params.profileMode]
  enabled = false
  title = "5h4rrK"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hii, I'm Sabhya Raj Mehta aka 5h4rrK."
  Content = [
  "I'm Sabhya Raj Mehta currently pursuing B.Tech CSE in Amrita Vishwa Vidhyapeetham. I'm DFIR enthusiast, playing CTFs with teambi0s & DFIR category lead @ bi0s."
]

  [[params.socialIcons]]
  name = "Github"
  title = "Join me on Github"
  url = "https://github.com/5h4rrK"

  [[params.socialIcons]]
  name = "X"
  title = "Join me on Twitter"
  url = "https://twitter.com/5h4rrK"

  [[params.socialIcons]]
  name = "linkedin"
  title = "Join me on LinkedIn"
  url = "https://www.linkedin.com/in/sabhya05/"

  [[params.socialIcons]]
  name = "Mail"
  iconSVG = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path d="M30.56 8.47a8 8 0 0 0-7-7 64.29 64.29 0 0 0-15.06 0 8 8 0 0 0-7 7 64.29 64.29 0 0 0 0 15.06 8 8 0 0 0 7 7 64.29 64.29 0 0 0 15.06 0 8 8 0 0 0 7-7 64.29 64.29 0 0 0 0-15.06zm-8.69 8 6.76-7.09a63.05 63.05 0 0 1 0 13zM8.7 3.42a63.65 63.65 0 0 1 14.6 0A6 6 0 0 1 28.1 7l-9.53 10h-5.14L3.9 7a6 6 0 0 1 4.8-3.58zm-5.36 19a63.05 63.05 0 0 1 0-13l6.76 7.09zm20 6.21a63.65 63.65 0 0 1-14.6 0 6 6 0 0 1-4.94-3.92l7.75-6.78.77.81A1 1 0 0 0 13 19h6a1 1 0 0 0 .72-.31l.77-.81 7.75 6.78a6 6 0 0 1-4.94 3.92z" data-name="email android app aplication phone"/></svg>'
  title = "Join me on Gmail"
  url = "mailto:sabhrajmeh05@gmail.com"

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
